core:
  config:
    proxy:
      proxy_required: false

    bootstrap:
      management_cidr: 192.168.123.0/24

    k8s-addons:
      loadbalancer: 192.168.123.81-192.168.123.90

    microceph_config:
      sunbeam-1.localdomain:
        osd_devices: /dev/vdc

    horizon:
      resources:
        custom_theme: /home/ubuntu/theme.tar.gz

software:
  juju:
    bootstrap_args:
      - --debug
      - --agent-version=3.2.4

  charms:
    glance-k8s:
      channel: 2024.1/candidate
      revision: 66
      config:
        debug: True
        pool-type: replicated

  terraform:
    hypervisor-plan:
      source: /home/ubuntu/deploy-openstack-hypervisor

storage:
  # to be added in https://github.com/canonical/canonical-openstack-docs/issues/204
